apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tengu-injector-webhook-deployment
  labels:
    app: tengu-injector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tengu-injector
    spec:
      serviceAccountName: tengu-injector
      containers:
        - name: tengu-injector
          image: sborny/tengu-injector:v1
          imagePullPolicy: Always
          args:
            - -tenguCfgFile=/etc/webhook/config/tenguconfig.yaml
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      volumes:
        - name: webhook-certs
          secret:
            secretName: tengu-injector-webhook-certs
        - name: webhook-config
          configMap:
            name: tengu-injector-webhook-configmap
