apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: tengu-injector-webhook-cfg
  labels:
    app: tengu-injector
webhooks:
  - name: injector.tengu-injector.io
    clientConfig:
      service:
        name: tengu-injector-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPRENDQWlDZ0F3SUJBZ0lKQVBocTNHVnUrbWM1TUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURERXdMakV3TGpFek9TNDFPVEFlRncweE9UQTBNak14TXpRMU1EaGFGdzB5T1RBME1qQXhNelExTURoYQpNQmN4RlRBVEJnTlZCQU1NRERFd0xqRXdMakV6T1M0MU9UQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFNWWM1ZEN0OUJScTJCb2lsN2dSNGZwSmJMSnhPdzUrWkY3VW5UbGpESkpNTlZ5ZWJwSFYKTG0zMUZTTzNOTStoOHgwMXZ1VE1VbEhMRldObUVhMXBlbnZVTlBZV21xM3d6ODcwNTZGTzZBaWZsTU8vejg4UgpUMDJmMTQvTjREbDUrSUFvbTE3emI3U2Vudk1KQlgyc08xQzlneEduVnY1SEFxbzd4VEg3dDFvaWJxZnNnajZ6ClhHUlpjT2FHSHBGRVByWWhqS2gvSTZsUlBNRmN0TUt6NlJPQjU4VXg2MGVNUVZEZGV1Z3U3eTNNWnFsN1pOUWEKekxmckcxcGRPUmFzQ1VKVExUM2VYSFNkVjNnZE1wcFhXdkpnUXJSZ1NmcXF0bEYrOGxJYXUxeDhzazRLUVFrWQpteDZMc3NTRG5ic0VyMHdOVExNN0xJWVIxMEZXUFloZjJnVUNBd0VBQWFPQmhqQ0JnekFkQmdOVkhRNEVGZ1FVCmR1bXBTUXNzYnkzWVFncHdZMzFEMXh1SnJFQXdSd1lEVlIwakJFQXdQb0FVZHVtcFNRc3NieTNZUWdwd1kzMUQKMXh1SnJFQ2hHNlFaTUJjeEZUQVRCZ05WQkFNTURERXdMakV3TGpFek9TNDFPWUlKQVBocTNHVnUrbWM1TUF3RwpBMVVkRXdRRk1BTUJBZjh3Q3dZRFZSMFBCQVFEQWdFR01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0E3aXUzCnJyN2srSmVjTHZIdklqaWRjeFVzcUVEQ2lGL0dkMlA0SDRTeTBxL0hSNXhndG9jNS9UaDJZT0cybm5rNGlORmUKb3VZcFZzSU9qdmRVaXVhekIzc0c3Z3ByV1ZKNGMrQloxekdZOXZoaVluRkRRUXZCZ2xUUEF6UTdVdGd0S0ZWVgoyWldCRVBLT2Z5RTY2ZUNvZzZZcGF0bHViWGpaampQbytUZThvRmY3Rmpmek9hL2w1L2RVL0I3VTJiZXZmYlpWCi9rbjB1S3JGRkJXVG4xMWJEQzRCeVhObmFZNmE4dkp3V2VHb3VOeUl6T3hiV3c0ZG8zamF3VWRlb05UWWpzMW4Kd096b2lwM29DRHNSTWdzb0tGK1hMUUVTZHVuUDBXK01yK2p4SkYrSWRXckFsYVF6TkdhdUFCVzYwRzl1TmgrdAo0U1VrOEVWMEQ4RVgvTmJHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["services"] 
    namespaceSelector:
      matchLabels:
        tengu-injector: enabled
