apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: tengu-injector-webhook-cfg
  labels:
    app: tengu-injector
webhooks:
  - name: injector.tengu-injector.io
    clientConfig:
      service:
        name: tengu-injector-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods", "services"]
    namespaceSelector:
      matchLabels:
        tengu-injector: enabled
