apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: tengu-injector-webhook-cfg
  labels:
    app: tengu-injector
webhooks:
  - name: tenug-injector.ugent.be
    clientConfig:
      service:
        name: tengu-injector-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPekNDQWlPZ0F3SUJBZ0lKQUxqWVBUOEhIM3FJTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmd4RmpBVUJnTlYKQkFNTURURXdMakUwTGpJd05pNHhNamt3SGhjTk1Ua3dNakV6TVRRMU5qVXhXaGNOTWprd01qRXdNVFExTmpVeApXakFZTVJZd0ZBWURWUVFEREEweE1DNHhOQzR5TURZdU1USTVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUF0YTdHQXNsZ0ZUdENoT2Q2UFZFa3BjY1ZzQUdmZVVuMFBBOC84MytvckJYMkZ4Tk8Kait6K1NtZHJtOWczRURoSDNucUZOb2hmL29QUHhMSWd3SmZOUFQ4SVgxQzMxd2xvczZjcnVWN2FYYkxRWGlVdwo2S1ZKWTJFL3NSbFNpRzcybmVxcDgyUmQ3ZlFPUW9Cd2FydFUvdUxldjJ6Rkg4bGN2eDcrSFJuNkY0QjJZLytqClcxbHFJRUNDM2doNjNFOFNjakNsVmpTcm0xbUozNld3dGhMN3htcWJpWEtpaHNwWFRYRnFUQThmMUVCdUtsVEoKd2VQWWhSeGtiU0dERjZhU1gvWlo3cjNYZnhtaVk4b0crL2Q5MHlzeUFOb0puNWVQTFQxNFR4T2x0WGF1S2VvWQpVellnbW54WDh2QkhwOGtUbmFKUzJ1ejRPaWllQmZXSWJ0eVVZUUlEQVFBQm80R0hNSUdFTUIwR0ExVWREZ1FXCkJCUW9Ec2lDekxJYnYyZUdDMFk3eUdPQlBOWUNSakJJQmdOVkhTTUVRVEEvZ0JRb0RzaUN6TElidjJlR0MwWTcKeUdPQlBOWUNScUVjcEJvd0dERVdNQlFHQTFVRUF3d05NVEF1TVRRdU1qQTJMakV5T1lJSkFMallQVDhISDNxSQpNQXdHQTFVZEV3UUZNQU1CQWY4d0N3WURWUjBQQkFRREFnRUdNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNNCmFzeis0YTlOOUZleUFTTXFOTDFSZk9FazU4RUF2Ykx2dnlPUG5tWmJid01wS3h6K2NvSW9WbG42bUk1aFhqS1gKTmxlcXlFWHJja2M2a0RXU0w1RW9HQVBwWEcxc0VQZDZGZE5PeVhoMnlwSHhLc28vSWpRb05EOHdVM05RcEVaZgpDMXQwaUtDSjh5ano2bFJ3YWdVYVl6S0JvZUVQdjd2UkJDZ3pHT2RtcEhOaVhJa3hsMDQ1NmF5TGhCZEVkUmQxCjZOaGQ1Rk9DbGE1akduS1ZJS3JIR1NSMUV5azlZYTgvODhNN3UxMmZ4Z2xvODdJa0VvUk1iKzZtOS9XeDBGd3cKa3pZVnY4WExDVWtILzByckpWZSttblBjcFBHa2ZGYVZaODk5MmlVRVAvUmlnT25vakl0cWt4aUV5T1gzZk81SgpnSGJySk5CTVY3M2pINzBhanQ5RwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        tengu-injector: enabled
