apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        tengu.io/consumes: "sse"
        tengu.io/relations: "sse-endpoint"
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep1
          image: tutum/curl
          command: ["/bin/sleep","infinity"]
          imagePullPolicy: IfNotPresent
