apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  labels:
<<<<<<< HEAD
    tengu.io/consumes: "sse"
    tengu.io/relations: "sse-endpoint"
=======
    # tengu.io/consumes: "sse"
    tengu.io/relationships: "full"
  annotations:
    tengu.io/consumes: "sse,db"
    tengu.io/relations: "sse-endpoint,db-endpoint"
>>>>>>> annotations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
        tengu.io/consumes: "sse"
        tengu.io/relations: "sse-endpoint"
    spec:
      containers:
        - name: sleep1
          image: tutum/curl
          command: ["/bin/sleep","infinity"]
          imagePullPolicy: IfNotPresent
