apiVersion: v1
kind: ConfigMap
metadata:
  name: relations-mutating-webhook
data:
  tenguconfig.yaml: |
    initContainers:
      - name: tengu-initcontainer
        image: ibcnservices/init-container
        imagePullPolicy: Always
