apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: relations-mutating-webhook
  labels:
    app: relations-mutating-webhook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: relations-mutating-webhook
    spec:
      serviceAccountName: tengu-controllers
      containers:
        - name: relations-mutating-webhook
          image: ibcnservices/relations-mutating-webhook:v1
          imagePullPolicy: Always
          args:
            - -tenguCfgFile=/etc/webhook/config/tenguconfig.yaml
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      volumes:
        - name: webhook-certs
          secret:
            secretName: tengu-injector-webhook-certs
        - name: webhook-config
          configMap:
            name: relations-mutating-webhook
