apiVersion: v1
kind: Service
metadata:
  name: relations-mutating-webhook
  labels:
    app: relations-mutating-webhook
spec:
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app: relations-mutating-webhook
