apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: relations-mutating-webhook
  labels:
    app: relations-mutating-webhook
webhooks:
  - name: relations-mutating-webhook.tengu.io
    clientConfig:
      service:
        name: relations-mutating-webhook
        namespace: default
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps", "extension"]
        apiVersions: ["v1"]
        resources: ["deployments"]
    namespaceSelector:
      matchLabels:
        tengu-injector: enabled
